
Create Procedure SPEmployeedata
AS 
BEGIN

SELECT Emp_id, Emp_Name, Emp_iDNo, dept_id, TOTALSALARY, DEPT_ROOMID  FROM Employee 

END

SPEMPLOYEEDATA 
EXEC SPEmployeedata 
EXECUTE SPEmployeedata 


ALTER PROCEDURE SPEMPLOYEEDATA
AS
BEGIN

SELECT EMP_ID, EMP_NAME, EMP_IDNO, DEPT_ID FROM Employee

END

SPEMPLOYEEDATA




ALTER PROC SPGETEMPLOYEEDATA_PARAMETER
@EMP_ID INT

AS
BEGIN

SELECT EMP_ID, EMP_NAME, EMP_IDNO,TOTALSALARY, DEPT_ROOMID  FROM Employee 
WHERE EMP_ID = @EMP_ID

END

SPGETEMPLOYEEDATA_PARAMETER 21



ALTER PROCEDURE SPGETEMPLOYEEDATA_PARAMETER
@EMP_ID INT

AS

BEGIN

SELECT EMP_ID, EMP_NAME, EMP_IDNO, TOTALSALARY, DEPT_ROOMID FROM Employee 
WHERE EMP_ID = @EMP_ID 

END